# Generated by Django 5.1.4 on 2025-01-12 00:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('tg_id', models.BigIntegerField(primary_key=True, serialize=False)),
                ('username', models.CharField(blank=True, max_length=255, null=True)),
                ('first_name', models.CharField(blank=True, max_length=255, null=True)),
                ('last_name', models.CharField(blank=True, max_length=255, null=True)),
                ('language_code', models.CharField(blank=True, max_length=10, null=True)),
                ('is_bot', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Coupon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=255, unique=True)),
                ('amount', models.IntegerField()),
                ('usage_limit', models.IntegerField(default=1)),
                ('usage_count', models.IntegerField(default=0)),
                ('is_used', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Tariff',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('duration', models.CharField(max_length=50)),
                ('price', models.FloatField()),
                ('total', models.FloatField()),
                ('original_price', models.FloatField(blank=True, null=True)),
                ('is_bestseller', models.BooleanField(default=False)),
                ('period_days', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Connection',
            fields=[
                ('tg_id', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='api.user')),
                ('balance', models.FloatField(default=0.0)),
                ('trial', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='CouponUsage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.BigIntegerField()),
                ('used_at', models.DateTimeField(auto_now_add=True)),
                ('coupon', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.coupon')),
            ],
        ),
        migrations.CreateModel(
            name='Key',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client_id', models.CharField(max_length=255)),
                ('email', models.CharField(max_length=255, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('expiry_time', models.BigIntegerField()),
                ('sub_id', models.CharField(max_length=255, unique=True)),
                ('total_gb', models.FloatField(default=100.0)),
                ('used_gb', models.FloatField(default=0.0)),
                ('is_active', models.BooleanField(default=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.user')),
            ],
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tg_id', models.BigIntegerField()),
                ('last_notification_time', models.DateTimeField(auto_now_add=True)),
                ('notification_type', models.CharField(max_length=255)),
            ],
            options={
                'unique_together': {('tg_id', 'notification_type')},
            },
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.FloatField()),
                ('payment_system', models.CharField(max_length=255)),
                ('status', models.CharField(default='success', max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('tg_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.user')),
            ],
        ),
        migrations.CreateModel(
            name='Referral',
            fields=[
                ('referred_user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='referred_tg_user', serialize=False, to='api.user')),
                ('reward_issued', models.BooleanField(default=False)),
                ('referrer_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='referrer_tg_user', to='api.user')),
            ],
        ),
    ]
