# Generated by Django 5.1.4 on 2024-12-25 07:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('tg_id', models.BigIntegerField(primary_key=True, serialize=False)),
                ('username', models.CharField(max_length=255, null=True)),
                ('first_name', models.CharField(max_length=255, null=True)),
                ('last_name', models.CharField(max_length=255, null=True)),
                ('language_code', models.CharField(max_length=10, null=True)),
                ('is_bot', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Coupon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=255, unique=True)),
                ('amount', models.IntegerField()),
                ('usage_limit', models.IntegerField(default=1)),
                ('usage_count', models.IntegerField(default=0)),
                ('is_used', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Referral',
            fields=[
                ('referred_tg_id', models.BigIntegerField(primary_key=True, serialize=False)),
                ('referrer_tg_id', models.BigIntegerField()),
                ('reward_issued', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Connection',
            fields=[
                ('tg_id', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='api.user')),
                ('balance', models.FloatField(default=0.0)),
                ('trial', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='CouponUsage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.BigIntegerField()),
                ('used_at', models.DateTimeField(auto_now_add=True)),
                ('coupon', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.coupon')),
            ],
        ),
        migrations.CreateModel(
            name='Key',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client_id', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254)),
                ('created_at', models.BigIntegerField()),
                ('expiry_time', models.BigIntegerField()),
                ('key', models.TextField()),
                ('server_id', models.CharField(default='cluster1', max_length=255)),
                ('notified', models.BooleanField(default=False)),
                ('notified_24h', models.BooleanField(default=False)),
                ('tg_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.user')),
            ],
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tg_id', models.BigIntegerField()),
                ('last_notification_time', models.DateTimeField(auto_now_add=True)),
                ('notification_type', models.CharField(max_length=255)),
            ],
            options={
                'unique_together': {('tg_id', 'notification_type')},
            },
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.FloatField()),
                ('payment_system', models.CharField(max_length=255)),
                ('status', models.CharField(default='success', max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('tg_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.user')),
            ],
        ),
    ]
