# Generated by Django 5.1.4 on 2025-01-12 01:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='key',
            name='total_gb',
        ),
        migrations.RemoveField(
            model_name='key',
            name='used_gb',
        ),
        migrations.AddField(
            model_name='key',
            name='total_bytes',
            field=models.BigIntegerField(default=107374182400),
        ),
        migrations.AddField(
            model_name='key',
            name='used_bytes',
            field=models.BigIntegerField(default=0),
        ),
    ]
