# Generated by Django 5.1.4 on 2025-01-12 02:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_remove_key_total_gb_remove_key_used_gb_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='key',
            name='access_token',
            field=models.CharField(default='itsaccess', max_length=255, unique=True),
            preserve_default=False,
        ),
    ]
