# Generated by Django 5.1.4 on 2025-01-12 04:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_key_access_token'),
    ]

    operations = [
        migrations.AddField(
            model_name='key',
            name='can_claim_gift',
            field=models.BooleanField(default=True),
        ),
    ]
