# Generated by Django 5.1.4 on 2025-01-18 09:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_key_can_claim_gift'),
    ]

    operations = [
        migrations.AddField(
            model_name='key',
            name='next_reset_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
