# Generated by Django 5.1.4 on 2025-01-19 08:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_key_next_reset_date'),
    ]

    operations = [
        migrations.RenameField(
            model_name='payment',
            old_name='tg_id',
            new_name='user',
        ),
        migrations.AddField(
            model_name='payment',
            name='payment_id',
            field=models.CharField(default=3637, max_length=255, unique=True),
            preserve_default=False,
        ),
    ]
