# Generated by Django 5.1.4 on 2025-01-02 19:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_remove_user_is_active'),
    ]

    operations = [
        migrations.AlterField(
            model_name='referral',
            name='referred_tg_id',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='referred_user', serialize=False, to='api.user'),
        ),
        migrations.AlterField(
            model_name='referral',
            name='referrer_tg_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='referrer_user', to='api.user'),
        ),
        migrations.AlterField(
            model_name='user',
            name='first_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='language_code',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='last_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='username',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
