# Generated by Django 5.1.4 on 2025-02-11 16:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_rename_tg_id_payment_user_payment_payment_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='utm_source',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
    ]
