# Generated by Django 5.1.4 on 2025-02-15 17:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_user_utm_source'),
    ]

    operations = [
        migrations.AddField(
            model_name='key',
            name='tried_to_connect',
            field=models.BooleanField(default=False),
        ),
    ]
