# Generated by Django 5.2.6 on 2025-09-23 09:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReferralReward',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bonus_days_awarded', models.PositiveIntegerField(default=7, verbose_name='Начислено бонусных дней')),
                ('awarded_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата начисления')),
                ('referral', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='reward_triggered_by', to='users.user', verbose_name='Кто принес бонус (приглашенный)')),
                ('referrer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rewards_given', to='users.user', verbose_name='Кто получил бонус (пригласивший)')),
            ],
            options={
                'verbose_name': 'Реферальное вознаграждение',
                'verbose_name_plural': 'Реферальные вознаграждения',
                'ordering': ['-awarded_at'],
            },
        ),
    ]
