[project]
name = "tugan-vpn"
version = "0.1.0"
description = ""
authors = [
    {name = "miderror",email = "miderror.dev@gmail.com"}
]
requires-python = ">=3.12, <4.0"
dependencies = [
    "django (>=6.0.6,<7.0.0)",
    "yookassa (>=3.11.0,<4.0.0)",
    "telegram-webapp-auth (>=3.1.0,<4.0.0)",
    "django-environ (>=0.13.0,<0.14.0)",
    "orjson (>=3.11.9,<4.0.0)",
    "granian (>=2.7.6,<3.0.0)",
    "psycopg[binary,pool] (>=3.3.4,<4.0.0)",
]

[tool.poetry]
package-mode = false

[build-system]
requires = ["poetry-core>=2.0.0,<3.0.0"]
build-backend = "poetry.core.masonry.api"
