# Generated by Django 5.2.7 on 2025-12-12 05:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='NotificationRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Название правила (для админа)')),
                ('trigger_hours_before_expiry', models.PositiveIntegerField(help_text='За сколько часов до окончания подписки отправить уведомление.', verbose_name='Отправить за (часов)')),
                ('message_template', models.TextField(help_text='Используйте {days} для дней и {hours} для часов. Пример: Ваша подписка истекает через {hours} часа(ов)!', verbose_name='Шаблон сообщения')),
                ('is_active', models.BooleanField(default=True, verbose_name='Правило активно')),
            ],
            options={
                'verbose_name': 'Правило уведомления',
                'verbose_name_plural': 'Правила уведомлений',
                'ordering': ['trigger_hours_before_expiry'],
            },
        ),
        migrations.CreateModel(
            name='SentNotification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sent_at', models.DateTimeField(auto_now_add=True, verbose_name='Время отправки')),
                ('subscription_end_date_at_send_time', models.DateTimeField(verbose_name='Дата окончания подписки в момент отправки')),
                ('rule', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='notifications.notificationrule', verbose_name='Правило')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.user', verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Отправленное уведомление',
                'verbose_name_plural': 'Отправленные уведомления',
                'unique_together': {('user', 'rule', 'subscription_end_date_at_send_time')},
            },
        ),
    ]
