# Generated by Django 5.2.7 on 2025-12-26 06:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='avatar',
            field=models.ImageField(blank=True, null=True, upload_to='avatars/', verbose_name='Кэшированный аватар'),
        ),
        migrations.AddField(
            model_name='user',
            name='avatar_updated_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Дата обновления аватара'),
        ),
    ]
