# Generated by Django 5.2.7 on 2025-12-13 18:57

import django_jsonform.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vpn', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vpnserver',
            name='api_password',
        ),
        migrations.RemoveField(
            model_name='vpnserver',
            name='api_url',
        ),
        migrations.RemoveField(
            model_name='vpnserver',
            name='api_username',
        ),
        migrations.AddField(
            model_name='vpnserver',
            name='config_template',
            field=models.TextField(default='vless://{uuid}@example.com:443?type=tcp&security=reality#{email}', help_text='Вставить полный конфиг для подключения, заменив UUID клиента на {uuid}.<br>Пример: vless://{uuid}@1.2.3.4:443?type=tcp&...#NAME', verbose_name='Шаблон конфига подключения'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='vpnserver',
            name='credentials',
            field=django_jsonform.models.fields.JSONField(default={'api_url': 'http://localhost', 'password': 'password', 'username': 'admin'}, help_text='Настройки подключения к панели 3x-ui', verbose_name='Доступы к API'),
            preserve_default=False,
        ),
    ]
