# Generated by Django 5.2.7 on 2025-11-01 00:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vpn', '0002_remove_tariff_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='tariff',
            name='display_name',
            field=models.CharField(default='test', help_text="Например: 1 месяц'", max_length=100, verbose_name='Название для фронтенда'),
            preserve_default=False,
        ),
    ]
