# Generated by Django 5.2.7 on 2025-11-01 00:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vpn', '0003_tariff_display_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tariff',
            name='display_name',
            field=models.CharField(help_text='Например: 1 месяц', max_length=100, verbose_name='Название для фронтенда'),
        ),
    ]
