# Generated by Django 5.2.7 on 2025-11-01 00:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vpn', '0004_alter_tariff_display_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subscription',
            name='total_paid',
        ),
        migrations.AddField(
            model_name='subscription',
            name='has_ever_connected',
            field=models.BooleanField(default=False, verbose_name='Пытался подключиться хотя бы раз'),
        ),
        migrations.AlterField(
            model_name='subscription',
            name='trial_activated',
            field=models.BooleanField(default=False, verbose_name="Пробный период активирован (кнопка '7 дней')"),
        ),
    ]
