# Generated by Django 5.2.7 on 2025-11-01 00:59

import backend.users.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='language_code',
            field=models.CharField(blank=True, max_length=15, null=True, verbose_name='Код языка'),
        ),
        migrations.AddField(
            model_name='user',
            name='last_name',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Фамилия'),
        ),
        migrations.AddField(
            model_name='user',
            name='utm_source',
            field=models.CharField(blank=True, max_length=64, null=True, validators=[backend.users.validators.validate_utm_source], verbose_name='UTM-метка'),
        ),
    ]
