# Generated by Django 5.2.7 on 2025-12-12 05:46

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tariff',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('display_name', models.CharField(help_text='Например: 1 месяц', max_length=100, verbose_name='Название для фронтенда')),
                ('duration_days', models.PositiveIntegerField(verbose_name='Длительность (дни)')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Цена (руб)')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активен')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Порядок сортировки')),
                ('is_bestseller', models.BooleanField(default=False, verbose_name='Бестселлер')),
                ('original_price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Старая цена (зачеркнутая)')),
            ],
            options={
                'verbose_name': 'Тариф',
                'verbose_name_plural': 'Тарифы',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='VpnServer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Название сервера (для админки)')),
                ('api_url', models.URLField(help_text='Пример: http://your_server_ip:2053', verbose_name='URL API 3x-ui')),
                ('api_username', models.CharField(max_length=100, verbose_name='Логин API')),
                ('api_password', models.CharField(max_length=100, verbose_name='Пароль API')),
                ('inbound_id', models.PositiveIntegerField(default=1, verbose_name='ID входящего подключения')),
                ('is_active', models.BooleanField(default=True, verbose_name='Сервер активен')),
            ],
            options={
                'verbose_name': 'VPN Сервер',
                'verbose_name_plural': 'VPN Серверы',
            },
        ),
        migrations.CreateModel(
            name='Subscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('end_date', models.DateTimeField(verbose_name='Дата окончания')),
                ('email', models.CharField(editable=False, max_length=255, unique=True)),
                ('sub_id', models.CharField(editable=False, max_length=255, unique=True)),
                ('access_token', models.CharField(db_index=True, editable=False, max_length=255, unique=True)),
                ('vless_uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('trial_activated', models.BooleanField(default=False, verbose_name="Пробный период активирован (кнопка '7 дней')")),
                ('has_ever_connected', models.BooleanField(default=False, verbose_name='Пытался подключиться хотя бы раз')),
                ('is_vpn_client_active', models.BooleanField(default=False, verbose_name='Клиент VPN активен в 3x-ui')),
                ('total_bytes_limit', models.BigIntegerField(default=268435456000, verbose_name='Лимит трафика (байты)')),
                ('used_bytes', models.BigIntegerField(default=0, verbose_name='Использовано трафика (байты)')),
                ('last_traffic_update', models.DateTimeField(blank=True, null=True, verbose_name='Последнее обновление трафика')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='subscription', to='users.user', verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Подписка',
                'verbose_name_plural': 'Подписки',
            },
        ),
    ]
