# Generated by Django 5.2.7 on 2025-12-24 02:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vpn', '0002_remove_vpnserver_api_password_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscription',
            name='trial_activated',
            field=models.BooleanField(default=False, verbose_name='Нажал кнопку с подарком'),
        ),
    ]
