# Generated by Django 5.2.7 on 2025-12-26 17:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vpn', '0003_alter_subscription_trial_activated'),
    ]

    operations = [
        migrations.CreateModel(
            name='SubscriptionManagement',
            fields=[
            ],
            options={
                'verbose_name': 'Управление подписками',
                'verbose_name_plural': 'Управление подписками',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('vpn.subscription',),
        ),
    ]
